### ISSUE TITLE
BPETrainer的most_frequent_combination函数运行报错：KeyError

### ISSUE THREAD

**Issue by yangxudong** [Yikai-Liao/efficient_bpe#1]
Traceback (most recent call last):
  File "/apsarapangu/disk2/weisu.yxd/efficient_bpe/./ebpe.py", line 416, in <module>
    a = BPETrainer(
  File "/apsarapangu/disk2/weisu.yxd/efficient_bpe/./ebpe.py", line 199, in train_from_file
    return self.train_from_iter(self.load_file(path, verbose), verbose)
  File "/apsarapangu/disk2/weisu.yxd/efficient_bpe/./ebpe.py", line 205, in train_from_iter
    comb, freq = self.most_frequent_combination()
  File "/apsarapangu/disk2/weisu.yxd/efficient_bpe/./ebpe.py", line 283, in most_frequent_combination
    ground_freq = self.word_pair_len[comb]
KeyError: ('', '下载')

**Comment by Yikai-Liao** [comment]
Please provide the corpus you used.

And, have you modify the ebpe.py?Theoretically, an empty string is not expected to appear in a token pair.

By the way, I now prefer to use English more on Github, and I'll rewrite the blog in English (Thanks for this issue for reminding me that I have this repository 😢).

**Comment by Yikai-Liao** [comment]
@yangxudong Any updates？

**Comment by yangxudong** [comment]
我知道原因了，这个是因为我对训练语料做了一些变化：corpus 定义为一个list，其中中文字符单独作为一个element，英文单词和数字串整体作为一个element（原因是不想它们被拆成子串，只想对中文分词）。报错的原因是因为对于输入的的每个char，它的length不再等于1，跟原始代码的假设不一致。

**Comment by yangxudong** [comment]
> Please provide the corpus you used.
> 
> And, have you modify the ebpe.py?Theoretically, an empty string is not expected to appear in a token pair.
> 
> By the way, I now prefer to use English more on Github, and I'll rewrite the blog in English (Thanks for this issue for reminding me that I have this repository 😢).

谢谢回复！现在我想了办法绕过了这个问题，就是在训练时把这种长度大于1的element都替换为 ’#‘ 了。

Sorry for my poor english !

**Comment by yangxudong** [comment]
顺便请教一个问题，BPE分词有一个问题就是一个比较长的vocab，比如“南辕北辙”，存在时，必然需要一个能够拼接成该vocab的子串也作为vocab存在。如 2+2的形式 （”南辕" + "北辙”），或者 （1 + 3）的形式（“南“ + ”辕北辙”），或者 3+1 的形式，这样vocab词表里就必然要存在 诸如 ”辕北辙” 或者 “南辕北" 这样的词，从而导致最终的分词结果里也可能出现这种分词结果。

有什么好的解决思路么？

**Comment by Yikai-Liao** [comment]
BPE是基于整体语料的统计数据进行分词的，更高频的词对会更优先地被合并（一种贪心算法）。如果最终的结果中出现了“辕北辙”这种token，那说明词表已经没有能够进一步合并的词对了，并且这种合并方式已经是较优的解。

由于BPE算法并不考虑语义，也不进行动态规划之类的操作，并且使用的词频数据是整个语料库的词频，其分词结果从原理上就是很难做到最优的。

不过对于中文而言，目前许多模型倾向于使用单个字作为token，不存在分词问题。而英文中的BPE，也更多地是用于基于一定的统计规律差分未登录词。Byte Level BPE 更加激进，可能会将一个utf-8字符拆分为多个token（例如utf-8表示的emoji）。对于这些未登录词，即使使用神经网络分词可能也不会有很好的泛化效果，还浪费算力。

分词是否与人一致，并不是很影响模型性能。而且对于一些语言来讲，其单词本身就会存在多种分词方法，并不唯一，有实验表明，使用不同的分词方法大致都能得到相似的性能，如果让模型尝试将不同分词方法得到的特征进行对齐，还能进一步提高模型的性能。

而且BPE词表中保留这些“子词”还可以用于BPE过程中使用Dropout 操作，即按照优先级该合并一些token时按照概率跳过合并操作。这样可以让最后得到的预料中出现这些子词，比如既有[南辕北辙]，也有[南辕，北辙]，[南，辕，北，辙]。这样，也能让模型更好地理解一些较大的token是由什么组成的，更好地建模token之间的关系。这种操作在早年做翻译的时候就被提出了，能涨点。

**Comment by yangxudong** [comment]
> BPE是基于整体语料的统计数据进行分词的，更高频的词对会更优先地被合并（一种贪心算法）。如果最终的结果中出现了“辕北辙”这种token，那说明词表已经没有能够进一步合并的词对了，并且这种合并方式已经是较优的解。
> 
> 由于BPE算法并不考虑语义，也不进行动态规划之类的操作，并且使用的词频数据是整个语料库的词频，其分词结果从原理上就是很难做到最优的。
> 
> 不过对于中文而言，目前许多模型倾向于使用单个字作为token，不存在分词问题。而英文中的BPE，也更多地是用于基于一定的统计规律差分未登录词。Byte Level BPE 更加激进，可能会将一个utf-8字符拆分为多个token（例如utf-8表示的emoji）。对于这些未登录词，即使使用神经网络分词可能也不会有很好的泛化效果，还浪费算力。
> 
> 分词是否与人一致，并不是很影响模型性能。而且对于一些语言来讲，其单词本身就会存在多种分词方法，并不唯一，有实验表明，使用不同的分词方法大致都能得到相似的性能，如果让模型尝试将不同分词方法得到的特征进行对齐，还能进一步提高模型的性能。
> 
> 而且BPE词表中保留这些“子词”还可以用于BPE过程中使用Dropout 操作，即按照优先级该合并一些token时按照概率跳过合并操作。这样可以让最后得到的预料中出现这些子词，比如既有[南辕北辙]，也有[南辕，北辙]，[南，辕，北，辙]。这样，也能让模型更好地理解一些较大的token是由什么组成的，更好地建模token之间的关系。这种操作在早年做翻译的时候就被提出了，能涨点。

谢谢回复！

**Comment by yangxudong** [comment]
> BPE是基于整体语料的统计数据进行分词的，更高频的词对会更优先地被合并（一种贪心算法）。如果最终的结果中出现了“辕北辙”这种token，那说明词表已经没有能够进一步合并的词对了，并且这种合并方式已经是较优的解。
> 
> 由于BPE算法并不考虑语义，也不进行动态规划之类的操作，并且使用的词频数据是整个语料库的词频，其分词结果从原理上就是很难做到最优的。
> 
> 不过对于中文而言，目前许多模型倾向于使用单个字作为token，不存在分词问题。而英文中的BPE，也更多地是用于基于一定的统计规律差分未登录词。Byte Level BPE 更加激进，可能会将一个utf-8字符拆分为多个token（例如utf-8表示的emoji）。对于这些未登录词，即使使用神经网络分词可能也不会有很好的泛化效果，还浪费算力。
> 
> 分词是否与人一致，并不是很影响模型性能。而且对于一些语言来讲，其单词本身就会存在多种分词方法，并不唯一，有实验表明，使用不同的分词方法大致都能得到相似的性能，如果让模型尝试将不同分词方法得到的特征进行对齐，还能进一步提高模型的性能。
> 
> 而且BPE词表中保留这些“子词”还可以用于BPE过程中使用Dropout 操作，即按照优先级该合并一些token时按照概率跳过合并操作。这样可以让最后得到的预料中出现这些子词，比如既有[南辕北辙]，也有[南辕，北辙]，[南，辕，北，辙]。这样，也能让模型更好地理解一些较大的token是由什么组成的，更好地建模token之间的关系。这种操作在早年做翻译的时候就被提出了，能涨点。

谢谢回复！解释得很到位，学到了！
